# Generated by Django 5.0.1 on 2024-03-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etud',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
