# Generated by Django 5.0.1 on 2024-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_remove_etud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='etud',
            name='imaage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
