# Generated by Django 5.0.1 on 2024-03-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_etud_imaage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etud',
            name='imaage',
        ),
    ]
